"""empty message

Revision ID: 79082a7a297c
Revises: 
Create Date: 2024-08-05 04:18:34.888301

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '79082a7a297c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('specialityid', sa.Integer(), nullable=True))
        batch_op.drop_constraint('agents_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'speciality', ['specialityid'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'customers', ['customerid'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('specialities')

    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_constraint('booking_ibfk_2', type_='foreignkey')
        batch_op.drop_constraint('booking_ibfk_1', type_='foreignkey')
        batch_op.drop_constraint('booking_ibfk_3', type_='foreignkey')
        batch_op.create_foreign_key(None, 'chefs', ['chef'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'caterers', ['caterer'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'customers', ['booker'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.drop_constraint('cart_ibfk_1', type_='foreignkey')
        batch_op.drop_constraint('cart_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'customers', ['customerid'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'products', ['productid'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('caterers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('specialityid', sa.Integer(), nullable=True))
        batch_op.drop_constraint('caterers_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'speciality', ['specialityid'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'customers', ['customerid'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('specialities')

    with op.batch_alter_table('chefs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('specialityid', sa.Integer(), nullable=True))
        batch_op.drop_constraint('chefs_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'customers', ['customerid'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'speciality', ['specialityid'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('specialities')

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_constraint('comments_ibfk_2', type_='foreignkey')
        batch_op.drop_constraint('comments_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'customers', ['commenterid'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'post', ['postid'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['email'])

    with op.batch_alter_table('gallery', schema=None) as batch_op:
        batch_op.drop_constraint('gallery_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'caterers', ['catererid'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('likes', schema=None) as batch_op:
        batch_op.drop_constraint('likes_ibfk_2', type_='foreignkey')
        batch_op.drop_constraint('likes_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'post', ['postid'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'customers', ['customerid'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('menu_item', schema=None) as batch_op:
        batch_op.drop_constraint('menu_item_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'menu', ['menuid'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('order_item', schema=None) as batch_op:
        batch_op.drop_constraint('order_item_ibfk_1', type_='foreignkey')
        batch_op.drop_constraint('order_item_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'products', ['productid'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'orders', ['orderid'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint('orders_ibfk_2', type_='foreignkey')
        batch_op.drop_constraint('orders_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'customers', ['customerid'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'payment', ['paymentid'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['email'])
        batch_op.drop_constraint('payment_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'customers', ['customerid'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_constraint('post_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'customers', ['posterid'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint('products_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'customers', ['customerid'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('wishlist', schema=None) as batch_op:
        batch_op.drop_constraint('wishlist_ibfk_2', type_='foreignkey')
        batch_op.drop_constraint('wishlist_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'customers', ['customerid'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'products', ['productid'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wishlist', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('wishlist_ibfk_1', 'customers', ['customerid'], ['id'])
        batch_op.create_foreign_key('wishlist_ibfk_2', 'products', ['productid'], ['id'])

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('products_ibfk_1', 'customers', ['customerid'], ['id'])

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('post_ibfk_1', 'customers', ['posterid'], ['id'])

    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('payment_ibfk_1', 'customers', ['customerid'], ['id'])
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('orders_ibfk_1', 'customers', ['customerid'], ['id'])
        batch_op.create_foreign_key('orders_ibfk_2', 'payment', ['paymentid'], ['id'])

    with op.batch_alter_table('order_item', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('order_item_ibfk_2', 'products', ['productid'], ['id'])
        batch_op.create_foreign_key('order_item_ibfk_1', 'orders', ['orderid'], ['id'])

    with op.batch_alter_table('menu_item', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('menu_item_ibfk_1', 'menu', ['menuid'], ['id'])

    with op.batch_alter_table('likes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('likes_ibfk_1', 'customers', ['customerid'], ['id'])
        batch_op.create_foreign_key('likes_ibfk_2', 'post', ['postid'], ['id'])

    with op.batch_alter_table('gallery', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('gallery_ibfk_1', 'caterers', ['catererid'], ['id'])

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('comments_ibfk_1', 'customers', ['commenterid'], ['id'])
        batch_op.create_foreign_key('comments_ibfk_2', 'post', ['postid'], ['id'])

    with op.batch_alter_table('chefs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('specialities', mysql.TEXT(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('chefs_ibfk_1', 'customers', ['customerid'], ['id'])
        batch_op.drop_column('specialityid')

    with op.batch_alter_table('caterers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('specialities', mysql.TEXT(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('caterers_ibfk_1', 'customers', ['customerid'], ['id'])
        batch_op.drop_column('specialityid')

    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('cart_ibfk_2', 'products', ['productid'], ['id'])
        batch_op.create_foreign_key('cart_ibfk_1', 'customers', ['customerid'], ['id'])

    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('booking_ibfk_3', 'chefs', ['chef'], ['id'])
        batch_op.create_foreign_key('booking_ibfk_1', 'customers', ['booker'], ['id'])
        batch_op.create_foreign_key('booking_ibfk_2', 'caterers', ['caterer'], ['id'])

    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('specialities', mysql.TEXT(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('agents_ibfk_1', 'customers', ['customerid'], ['id'])
        batch_op.drop_column('specialityid')

    # ### end Alembic commands ###
